services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - calculator-net

  # NATS JetStream
  nats:
    image: nats:latest
    command: ["-js", "-m", "${NATS_MONITOR_PORT}"]
    ports:
      - "${NATS_CLIENT_PORT}:4222"   # Клиентские соединения
      - "${NATS_MONITOR_PORT}:8222"   # Веб-интерфейс мониторинга
    networks:
      - calculator-net

  # Сервис storage (должен стать gRPC сервером + NATS consumer)
  calculator-storage:
    build:
      context: ../calculator-storage
    ports:
      - "${STORAGE_GRPC_PORT}:50051"   # gRPC порт
    environment:
      NATS_URL: ${NATS_INTERNAL_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
    networks:
      - calculator-net

  # Сервис api (HTTP API + NATS publisher + gRPC client)
  calculator-api:
    build:
      context: ../calculator-api
    ports:
      - "${API_PORT}:8080"   # HTTP порт API
    environment:
      NATS_URL: ${NATS_INTERNAL_URL}
      STORAGE_SERVICE_URL: ${STORAGE_SERVICE_URL}
    depends_on:
      - nats
      - calculator-storage
    networks:
      - calculator-net

networks:
  calculator-net:
    driver: bridge

volumes:
  postgres-data: